/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardProjectComponent: typeof import('./src/components/CardProjectComponent.vue')['default']
    CarouselComponent: typeof import('./src/components/CarouselComponent.vue')['default']
    TimelineComponent: typeof import('./src/components/TimelineComponent.vue')['default']
  }
}
